# Generated by Django 3.2.4 on 2021-06-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20210613_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='GraphImage',
            field=models.ImageField(null=True, upload_to='func_folder/', verbose_name='График'),
        ),
    ]
