# Generated by Django 3.2.4 on 2021-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_test_graphimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='GraphDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='test',
            name='GraphT',
            field=models.DateTimeField(blank=True, null=True, verbose_name='t'),
        ),
    ]
