# Generated by Django 3.2.4 on 2021-06-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20210614_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='GraphDateTime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата'),
        ),
    ]
