# Generated by Django 3.2.4 on 2021-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_test_graphdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='GraphDateTime',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='test',
            name='GraphT',
            field=models.DateTimeField(verbose_name='t'),
        ),
    ]
