# Generated by Django 3.2.4 on 2021-06-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20210614_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='GraphT',
        ),
        migrations.AlterField(
            model_name='test',
            name='GraphDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
