# Generated by Django 3.2.4 on 2021-06-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_test_graphfuncid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='GraphId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
